import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { ChangeEvent, useState } from "react";
import { round, toCelsius, toFahrenheit } from "../utils/utils";
import { useDarkMode } from "../hooks/useDarkMode";

const format = (targetValue: string, degree: number) => {
  return targetValue !== "" ? degree.toString() : targetValue;
};

const Home: NextPage = () => {
  const [degreeCelsius, setDegreeCelsius] = useState("");
  const [degreeFahrenheit, setDegreeFahrenheit] = useState("");
  const [isDarkMode, setDark] = useDarkMode();

  const handleCelsiusInput = (event: ChangeEvent<HTMLInputElement>) => {
    const nextDegree = round(toFahrenheit(Number(event.target.value)), 100);
    setDegreeCelsius(event.target.value);
    setDegreeFahrenheit(format(event.target.value, nextDegree));
  };

  const handleFahrenheitInput = (event: ChangeEvent<HTMLInputElement>) => {
    const nextDegree = round(toCelsius(Number(event.target.value)), 100);
    setDegreeFahrenheit(event.target.value);
    setDegreeCelsius(format(event.target.value, nextDegree));
  };

  return (
    <div
      className={
        "dark:bg-black dark:text-white min-h-screen flex justify-center"
      }
    >
      <Head>
        <title>Temperature Converter App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"flex flex-col justify-center"}>
        <span className={"text-right"}>
          <Image
            src={isDarkMode ? "/light-mode.svg" : "/dark-mode.svg"}
            alt={isDarkMode ? "light" : "dark"}
            width={48}
            height={48}
            onClick={() => setDark(!isDarkMode)}
            className={"cursor-pointer"}
          ></Image>
        </span>
        <h1 className={"text-6xl font-bold mb-12 text-center"}>
          Temperature Converter
        </h1>
        <div className={"flex"}>
          <div className="flex flex-col items-start p-2">
            <div className={"text-4xl font-bold mb-4"}>Celsius</div>
            <div className={"flex"}>
              <input
                className={
                  "text-2xl appearance-none bg-transparent border-b-2 border-gray-400 w-full text-gray-700 mr-3 py-1 px-2 leading-tight focus:outline-none focus:border-sky-400/80 dark:placeholder-white dark:text-white"
                }
                value={degreeCelsius}
                onChange={handleCelsiusInput}
                placeholder={"0"}
                type={"number"}
              ></input>
              <span className={"text-4xl font-bold"}>°C</span>
            </div>
          </div>
          <div className={"mx-16 flex"}>
            <Image
              src={
                isDarkMode ? "/equal-icon-white.svg" : "/equal-icon-black.svg"
              }
              className={"fill-white"}
              alt="equal"
              width={64}
              height={64}
            ></Image>
          </div>
          <div className="flex flex-col items-start p-2">
            <div className={"text-4xl font-bold mb-4"}>Fahrenheit</div>
            <div className={"flex"}>
              <input
                className={
                  "text-2xl appearance-none bg-transparent border-b-2 border-gray-400 w-full text-gray-700 mr-3 py-1 px-2 leading-tight focus:outline-none focus:border-rose-400/80 dark:placeholder-white dark:text-white"
                }
                value={degreeFahrenheit}
                onChange={handleFahrenheitInput}
                placeholder={"32"}
                type={"number"}
              ></input>
              <span className={"text-4xl font-bold"}>°F</span>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
