import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { ChangeEvent, useMemo, useState } from "react";
import { round, toCelsius, toFahrenheit } from "../utils/utils";
import { useDarkMode } from "../hooks/useDarkMode";
import { InputDegree } from "../component/InputDegree";
import { DegreeInfo } from "../Type/Type";

const format = (targetValue: string, degree: number) => {
  return targetValue !== "" ? degree.toString() : targetValue;
};

const celsius: DegreeInfo = {
  unitName: "Celsius",
  unitSymbol: "°C",
  defaultValue: 0,
};

const fahrenheit: DegreeInfo = {
  unitName: "Fahrenheit",
  unitSymbol: "°F",
  defaultValue: 0,
};

const Home: NextPage = () => {
  const [degreeCelsius, setDegreeCelsius] = useState("");
  const [degreeFahrenheit, setDegreeFahrenheit] = useState("");
  const [isDarkMode, setDark] = useDarkMode();

  const handleCelsiusInput = (event: ChangeEvent<HTMLInputElement>) => {
    const nextDegree = round(toFahrenheit(Number(event.target.value)), 100);
    setDegreeCelsius(event.target.value);
    setDegreeFahrenheit(format(event.target.value, nextDegree));
  };

  const handleFahrenheitInput = (event: ChangeEvent<HTMLInputElement>) => {
    const nextDegree = round(toCelsius(Number(event.target.value)), 100);
    setDegreeFahrenheit(event.target.value);
    setDegreeCelsius(format(event.target.value, nextDegree));
  };

  return (
    <div
      className={
        "dark:bg-black dark:text-white min-h-screen flex justify-center"
      }
    >
      <Head>
        <title>Temperature Converter App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"flex flex-col justify-center"}>
        <span className={"text-right"}>
          <Image
            src={isDarkMode ? "/light-mode.svg" : "/dark-mode.svg"}
            alt={isDarkMode ? "light" : "dark"}
            width={48}
            height={48}
            onClick={() => setDark(!isDarkMode)}
            className={"cursor-pointer"}
          ></Image>
        </span>
        <h1 className={"text-6xl font-bold mb-12 text-center"}>
          Temperature Converter
        </h1>
        <div className={"flex"}>
          <InputDegree
            unitName={celsius.unitName}
            unitSymbol={celsius.unitSymbol}
            placeHolderValue={celsius.defaultValue.toString()}
            currentValue={degreeCelsius}
            onChangeHandler={handleCelsiusInput}
          />
          <div className={"mx-16 flex"}>
            <Image
              src={
                isDarkMode ? "/equal-icon-white.svg" : "/equal-icon-black.svg"
              }
              className={"fill-white"}
              alt="equal"
              width={64}
              height={64}
            ></Image>
          </div>
          <InputDegree
            unitName={fahrenheit.unitName}
            unitSymbol={fahrenheit.unitSymbol}
            placeHolderValue={fahrenheit.defaultValue.toString()}
            currentValue={degreeFahrenheit}
            onChangeHandler={handleFahrenheitInput}
          />
        </div>
      </main>
    </div>
  );
};

export default Home;
